# Lint Dockerfile
# -:6 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
# -:28 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
# -:28 SC2086 info: Double quote to prevent globbing and word splitting.
# -:28 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
# -:90 SC2086 info: Double quote to prevent globbing and word splitting.

# Lint Dockerfile.alpine
# -:3 DL3029 warning: Do not use --platform flag with FROM
# -:8 DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
# -:23 DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
# -:23 DL3019 info: Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*` when done installing packages

# Lint Dockerfile.buster
# -:10 SC2109 error: Instead of [ a || b ], use [ a ] || [ b ].
ignored:
  - DL3008
  - SC2086
  - DL4006
  - DL3029
  - DL3018
  - DL3019
  - SC2109
