#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# https://github.com/jnovack/docker-multi-arch-hooks/tree/master/build/package/hooks
# https://gist.github.com/rossf7/664dc1eb02f514993c7215d37058965c

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.

set -x

source .env.build
export DOCKER_BUILDKIT=1

env

#echo "Adding custom builder"
#docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#docker buildx create --name multiarch --driver docker-container --use

echo "Build php:7.4-fpm-buster"
docker buildx build \
    --file $DOCKERFILE_PATH \
    --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
    --tag $IMAGE_NAME \
    --build-arg VERSION=$PHP74 \
    --build-arg VARIANT=fpm \
    --progress=plain \
    --no-cache \
    --push .
