name: PHP 7.4/8.0 image sets CI

on:

#  push:
#    branches: main

#  workflow_dispatch:
#    inputs:
#      tags:
#        description: 'Cerbot version tag'
#        required: true
#        default: 'v1.10.1'
#      latest:
#        description: 'Is latest?'
#        required: true
#        default: 'yes'

  workflow_dispatch:

jobs:

  Buster74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
        #  docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build php:7.4-zts-buster
        run: |
          docker buildx build \
            --file Dockerfile.buster.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:7.4.16-zts-buster \
            --tag carlesbarreda/php:7.4-zts-buster \
            --build-arg VERSION=7.4.16 \
            --build-arg VARIANT=zts \
            --progress=plain \
            --no-cache \
            --push .

      - name: Build php:7.4-fpm-buster
        run: |
          docker buildx build \
            --file Dockerfile.buster.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:7.4.16-fpm-buster \
            --tag carlesbarreda/php:7.4-fpm-buster \
            --build-arg VERSION=7.4.16 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Alpine74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
        #  docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build php:7.4-zts-alpine
        run: |
          docker buildx build \
            --file Dockerfile.alpine.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:7.4.16-zts-alpine \
            --tag carlesbarreda/php:7.4-zts-alpine \
            --build-arg VERSION=7.4.16 \
            --build-arg VARIANT=zts \
            --progress=plain \
            --no-cache \
            --push .

      - name: Build php:7.4-fpm-alpine
        run: |
          docker buildx build \
            --file Dockerfile.alpine.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:7.4.16-fpm-alpine \
            --tag carlesbarreda/php:7.4-fpm-alpine \
            --build-arg VERSION=7.4.16 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Buster80:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
        #  docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build php:8.0-zts-buster
        run: |
          docker buildx build \
            --file Dockerfile.buster.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:8.0.3-zts-buster \
            --tag carlesbarreda/php:8.0-zts-buster \
            --build-arg VERSION=8.0.3 \
            --build-arg VARIANT=zts \
            --progress=plain \
            --no-cache \
            --push .

      - name: Build php:8.0-fpm-buster
        run: |
          docker buildx build \
            --file Dockerfile.buster.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:8.0.3-fpm-buster \
            --tag carlesbarreda/php:8.0-fpm-buster \
            --build-arg VERSION=8.0.3 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Alpine80:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
        #  docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build php:8.0-fpm-alpine
        run: |
          docker buildx build \
            --file Dockerfile.alpine.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:8.0.3-fpm-alpine \
            --tag carlesbarreda/php:8.0-fpm-alpine \
            --tag carlesbarreda/php:latest \
            --build-arg VERSION=8.0.3 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .
