name: Docker Image CI
on:
  schedule:
    - cron: '00 23 * * 0'

  push:
    branches: [ "main" ]
    tags: [ '*.*.*' ]

  release:
    types: [published]

  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  #REGISTRY: 'ghcr.io'
  REGISTRY: 'docker.io'
  # github.repository as <account>/<repo>
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: 'carlesbarreda/php'
  LATEST_OS: 'alpine'
  LATEST_VER: '8.3'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #version: ['7.4','8.0']
        #os: [bullseye,alpine]
        #version: ['8.1','8.2','8.3']
        #os: [bullseye,bookworm,alpine]
        version: ['8.1','8.2','8.3','8.4']
        os: [bullseye,bookworm,alpine]
        platform: [linux/amd64,linux/arm64/v8,linux/arm/v7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Last Docker Image Release
        run: |
          TAGS=$(curl -s 'https://hub.docker.com/v2/repositories/library/php/tags/?page_size=10000&page=1&name=${{ matrix.version }}%25-fpm-${{ matrix.os }}' | jq '.results[] | {(.name): .images[].digest}')
          DIGEST=$(echo $TAGS | jq . | awk -F': ' '/"${{ matrix.version }}-fpm-${{ matrix.os }}"/ { print $2 }' | head -1)
          RELEASE=$(echo $TAGS | jq . | grep $DIGEST | cut -d":" -f1 | cut -d"\"" -f2 | cut -d"-" -f1 | grep -v fpm | sort -r | head -1)
          [ ${{ matrix.os == env.LATEST_OS && matrix.version == env.LATEST_VER }} ] && echo "LATEST=$RELEASE" >> $GITHUB_ENV
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Check Tag Exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: checkTag
        with: 
          tag: ${{ env.RELEASE }}

      - name: Check If Need Build
        run: |
          BUILD=false
          LATEST_BUILD=false
          [[ ${{ steps.checkTag.outputs.exists != true }} ]] && BUILD=true
          [[ '${{ github.event_name }}' == 'push' ]] && BUILD=true
          [[ '${{ github.event_name }}' == 'pull_request' ]] && BUILD=false
          [[ ${{ matrix.os == env.LATEST_OS && matrix.version == env.LATEST_VER }} ]] && LATEST_BUILD=$BUILD
          echo "LATEST_BUILD=$LATEST_BUILD" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      - name: Set up QEMU
        if: env.BUILD == 'true'
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        if: env.BUILD == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Cache Docker layers
        if: env.BUILD == 'true'
        uses: actions/cache@v4
        id: cache
        env:
          cache-name: cache-buildx
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.version }}-fpm-${{ matrix.os }}-${{ env.PLATFORM_PAIR }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.version }}-fpm-${{ matrix.os }}-${{ env.PLATFORM_PAIR }}

      - name: Login to Docker Hub
        if: env.BUILD == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        if: env.BUILD == 'true'
        id: meta-image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.RELEASE }}-fpm-${{ matrix.os }}
            ${{ matrix.version }}-fpm-${{ matrix.os }}
            ${{ matrix.os == env.LATEST_OS && matrix.version == env.LATEST_VER && 'latest' || '' }}
          labels: |
            org.opencontainers.image.authors=${{ secrets.AUTHORS }}
            org.opencontainers.image.vendor=${{ secrets.VENDOR }}
            org.opencontainers.image.version=${{ env.RELEASE }}

      - name: Build images
        if: env.BUILD == 'true'
        id: docker-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.${{ matrix.version }}.${{ matrix.os }}
          platforms: ${{ matrix.platform }}
          #tags: ${{ steps.meta-image.outputs.tags }}
          labels: ${{ steps.meta-image.outputs.labels }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta-image.outputs.json).labels['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.meta-image.outputs.json).labels['org.opencontainers.image.version'] }}
            BASEIMAGE=${{ matrix.os }}
            REVISION=${{ fromJSON(steps.meta-image.outputs.json).labels['org.opencontainers.image.revision'] }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: Move cache
        if: env.BUILD == 'true'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Results
        run: |
          mkdir -p /tmp/${{ matrix.version }}/${{ matrix.os }}
          echo "BUILD=${{ env.BUILD }}" >> "/tmp/${{ matrix.version }}/${{ matrix.os }}/env"
          echo "RELEASE=${{ env.RELEASE }}" >> "/tmp/${{ matrix.version }}/${{ matrix.os }}/env"
          echo "LATEST_BUILD=${{ env.LATEST_BUILD }}" >> "/tmp/${{ matrix.version }}/${{ matrix.os }}/env"
          echo "LATEST=${{ env.LATEST }}" >> "/tmp/${{ matrix.version }}/${{ matrix.os }}/env"

      - name: Export digest
        if: env.BUILD == 'true'
        run: |
          mkdir -p /tmp/${{ matrix.version }}/${{ matrix.os }}/digests
          digest="${{ steps.docker-image.outputs.digest }}"
          touch "/tmp/${{ matrix.version }}/${{ matrix.os }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}-${{ matrix.os }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/${{ matrix.version }}/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge image
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        #version: ['7.4','8.0']
        #os: [bullseye,alpine]
        version: ['8.1','8.2','8.3']
        os: [bullseye,bookworm,alpine]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/${{ matrix.version }}
          pattern: ${{ matrix.version }}-${{ matrix.os }}-*
          merge-multiple: true

      - name: Get env
        run: |
          cat "/tmp/${{ matrix.version }}/${{ matrix.os }}/env" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: env.BUILD == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Extract Docker metadata
        if: env.BUILD == 'true'
        id: meta-image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.RELEASE }}-fpm-${{ matrix.os }}
            ${{ matrix.version }}-fpm-${{ matrix.os }}
            ${{ matrix.os == env.LATEST_OS && matrix.version == env.LATEST_VER && 'latest' || '' }}
          labels: |
            org.opencontainers.image.authors=${{ secrets.AUTHORS }}
            org.opencontainers.image.vendor=${{ secrets.VENDOR }}
            org.opencontainers.image.version=${{ env.RELEASE }}

      - name: Login to Docker Hub
        if: env.BUILD == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create manifest list and push
        if: env.BUILD == 'true'
        working-directory: /tmp/${{ matrix.version }}/${{ matrix.os }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.IMAGE_NAME }}@sha256:%s ' *)          

      - name: Inspect image
        if: env.BUILD == 'true'
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ steps.meta-image.outputs.version }}

      - name: Create results
        run: |
          mkdir -p /tmp/results

      - name: Add image tag
        if: env.BUILD == 'true'
        run: |
          mkdir -p /tmp/results/${{ matrix.version }}
          IMAGE=${{ env.IMAGE_NAME }}
          echo "${IMAGE/\//\\/}:${{ env.LATEST }}-fpm-${{ matrix.os }}" >> "/tmp/results/${{ matrix.version }}/${{ matrix.os }}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.version }}-${{ matrix.os }}
          path: /tmp/results/*
          if-no-files-found: error
          retention-days: 1

  update:
    name: Update README.md
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/results
          pattern: results-*
          merge-multiple: true

      - name: Update README.md
        run: |
          COMMIT=false
          VERS=$(cd /tmp/results; ls -d *)
          if [[ -n $VERS ]]; then
            for V in $VERS; do
              T=$(S='- '; for I in $(cat /tmp/results/$V/*); do echo -n "${S}${I}"; S=', '; done)
              sed -i "s/## PHP $V Docker Image Tags/## PHP $V Docker Image Tags\n$T/g" README.md
            done
            COMMIT=true
          fi
          echo "COMMIT=$COMMIT" >> $GITHUB_ENV

      - name: Commit & Push changes
        if: env.COMMIT == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "Automated README.md update"
          git push

  #tags:
  #  name: Create tags
  #  runs-on: ubuntu-latest
  #  needs: [update]
  #  strategy:
  #    matrix:
  #      #version: ['7.4','8.0']
  #      #os: [bullseye,alpine]
  #      version: ['8.1','8.2','8.3']
  #      os: [bullseye,bookworm,alpine]
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4

  #    - name: Download digests
  #      uses: actions/download-artifact@v4
  #      with:
  #        path: /tmp/${{ matrix.version }}
  #        pattern: ${{ matrix.version }}-${{ matrix.os }}-*
  #        merge-multiple: true

  #    - name: Get env
  #      run: |
  #        cat "/tmp/${{ matrix.version }}/${{ matrix.os }}/env" >> $GITHUB_ENV

  #    - name: Create tag
  #      if: env.BUILD == 'true'
  #      uses: actions/github-script@v7
  #      with:
  #        github-token: ${{ github.token }}
  #        #github-token: ${{ secrets.GITHUB_TOKEN  }}
  #        script: |
  #          github.rest.git.createRef({
  #            owner: context.repo.owner,
  #            repo: context.repo.repo,
  #            ref: "refs/tags/${{ env.LATEST }}-fpm-${{ matrix.os }}",
  #            sha: context.sha
  #          })

# Error build 8.3 with imagick extension
# Transient Error when Building Imagick in php 8.3.x on amd64 on alpine #643
# https://github.com/Imagick/imagick/issues/643

# https://docs.docker.com/build/ci/github-actions/cache/#local-cache
# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
# https://docs.docker.com/reference/cli/docker/buildx/build/#output
# https://github.com/docker/metadata-action?tab=readme-ov-file#outputs
# https://github.com/marketplace/actions/aqua-security-trivy#using-trivy-with-github-code-scanning
# https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

# https://github.com/docker/setup-qemu-action
# https://github.com/docker/setup-buildx-action
# https://github.com/docker/build-push-action/issues/755#issuecomment-1378273495
# https://github.com/docker/build-push-action/issues/755#issuecomment-1378680855
# https://github.com/marketplace/actions/cache
# https://github.com/actions/cache
# https://docs.docker.com/build/ci/github-actions/cache/#local-cache
# https://github.com/docker/login-action
# https://github.com/docker/metadata-action

# https://github.com/docker/setup-buildx-action
# https://github.com/docker/build-push-action/issues/755#issuecomment-1378273495
# https://github.com/docker/build-push-action/issues/755#issuecomment-1378680855
# https://github.com/docker/metadata-action
# https://github.com/docker/login-action
