name: PHP 7.4 / 8.0 image sets CI

on:

#  push:
#    branches: main

#  workflow_dispatch:
#    inputs:
#      tags:
#        description: 'Cerbot version tag'
#        required: true
#        default: 'v1.10.1'
#      latest:
#        description: 'Is latest?'
#        required: true
#        default: 'yes'

  workflow_dispatch:

jobs:

  Buster74:
    name: "PHP 7.4 buster"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/actions/starter-workflows/issues/68
      # https://github.com/firepress-org/rclone-in-docker/blob/master/.github/workflows/ci_dockerfile_is_master.yml
      - name: Set env from file
        run: grep -e ^PHP74.*= .env.build >> $GITHUB_ENV
      - name: Build php:7.4-fpm-buster
        if: ${{ env.PHP74 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.buster \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:$PHP74-fpm-buster \
            --tag carlesbarreda/php:7.4-fpm-buster \
            --build-arg VERSION=$PHP74 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Alpine74:
    name: "PHP 7.4 alpine"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/actions/starter-workflows/issues/68
      - name: Set env from file
        run: grep -e ^PHP74.*= .env.build >> $GITHUB_ENV
      - name: Build php:7.4-fpm-alpine
        if: ${{ env.PHP74 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.alpine \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:$PHP74-fpm-alpine \
            --tag carlesbarreda/php:7.4-fpm-alpine \
            --build-arg VERSION=$PHP74 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Buster80:
    name: "PHP 8.0 buster"
    needs: [Buster74]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/actions/starter-workflows/issues/68
      - name: Set env from file
        run: grep -e ^PHP80.*= .env.build >> $GITHUB_ENV
      - name: Build php:8.0-fpm-buster
        if: ${{ env.PHP80 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.buster \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:$PHP80-fpm-buster \
            --tag carlesbarreda/php:8.0-fpm-buster \
            --build-arg VERSION=$PHP80 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Alpine80:
    name: "PHP 8.0 alpine"
    needs: [Alpine74]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Trigger docker hub build
        run: |
          curl -H "Content-Type: application/json" \
            --data '{"source_type": "Branch", "source_name": "main"}' \
            -X POST "https://hub.docker.com/api/build/v1/source/da887842-4973-4f57-a0ed-86ce3de097ed/trigger/26a41857-b0e1-40a4-85e0-b7f38719e5c2/call/";
      # https://github.com/actions/starter-workflows/issues/68
      - name: Set env from file
        run: grep -e ^PHP80.*= .env.build >> $GITHUB_ENV
      - name: Build php:8.0-fpm-alpine
        if: ${{ env.PHP80 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.alpine \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/php:$PHP80-fpm-alpine \
            --tag carlesbarreda/php:8.0-fpm-alpine \
            --tag carlesbarreda/php:latest \
            --build-arg VERSION=$PHP80 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .
