name: Testing CI

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1 of 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/actions/starter-workflows/issues/68
      # https://github.com/firepress-org/rclone-in-docker/blob/master/.github/workflows/ci_dockerfile_is_master.yml
      - name: Set env
        run: grep -e ^PHP74.*= .env.build >> $GITHUB_ENV
      - name: Test $PHP74
        if: PHP74 != ''
        run: echo Testing owner/name:$PHP74-tag
      - name: Test $PHP80
        if: PHP80 != ''
        run: echo Testing owner/name:$PHP80-tag

  job2:
    name: Job 2 of 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/actions/starter-workflows/issues/68
      # https://github.com/firepress-org/rclone-in-docker/blob/master/.github/workflows/ci_dockerfile_is_master.yml
      - name: Set env from file
        run: grep -e ^PHP80.*= .env.build >> $GITHUB_ENV
      - name: Test $PHP74
        if: PHP74 != ''
        run: echo Testing owner/name:$PHP74-tag
      - name: Test $PHP80
        if: PHP80 != ''
        run: echo Testing owner/name:$PHP80-tag
